/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.sebas.transpomex.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.COPY_ATTRIBUTES;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import me.sebas.transpomex.config.Configuracion;
import me.sebas.transpomex.db.DBCon;
import me.sebas.transpomex.facturas.Direccion;
import me.sebas.transpomex.facturas.Factura;
import me.sebas.transpomex.facturas.Fecha;
import me.sebas.transpomex.reportes.ReportesCSV;
import me.sebas.transpomex.vehiculo.Vehiculo;
import org.joda.time.Days;
import org.joda.time.LocalDateTime;

/**
 *
 * @author deckard
 */
public class VehiculosGui extends javax.swing.JFrame {

    private String tiposEnvio[] = {"Local", "Nacional"};
    private JFileChooser fc = null;
    private DBCon db;
    private File selectedImg;
    private DefaultListModel vListModel;
    private DecimalFormat numFormat = new DecimalFormat("##.##");

    public VehiculosGui() {
        fc = new JFileChooser();
        db = new DBCon();
        vListModel = new DefaultListModel<>();
        initComponents();
        java.time.LocalDateTime date = java.time.LocalDateTime.now();
        diaSpinner.setValue(date.getDayOfMonth());
        mesSpinner.setSelectedIndex(date.getMonth().getValue() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        vehiculosTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mostrar = new javax.swing.JPanel();
        jPanel3 = new ImagePanel("resources/default.jpg");
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        marcaLabel = new javax.swing.JLabel();
        capCargaLabel = new javax.swing.JLabel();
        volCargaLabel = new javax.swing.JLabel();
        kmRecorridosLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        reportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        registrar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        marcasCombo = new javax.swing.JComboBox<>(db.obtenerMarcas().toArray(new String[0]));
        modeloTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        volCargaSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        capCargaSpinner = new javax.swing.JSpinner();
        openImageButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        registrarButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        matrTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        anioSpinner = new javax.swing.JSpinner();
        factuarasTab = new javax.swing.JPanel();
        nuevo = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        calleTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        coloniaTF = new javax.swing.JTextField();
        municipioTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        estadoTF = new javax.swing.JComboBox<>(db.obtenerEstados().toArray(new String[0]));
        tipoEnvioCombo = new javax.swing.JComboBox<>(tiposEnvio);
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        diaSpinner = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        mesSpinner = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cajasRadio = new javax.swing.JRadioButton();
        cajasSpinner = new javax.swing.JSpinner();
        dimensionesRadio = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        anchoSpinner = new javax.swing.JSpinner();
        altoSpinner = new javax.swing.JSpinner();
        profSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jlabel23 = new javax.swing.JLabel();
        jlabel24 = new javax.swing.JLabel();
        costoLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pesoSpinner = new javax.swing.JSpinner();
        anioSpinnerEnvio = new javax.swing.JSpinner();
        enviarButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        buscarTF = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        reporteEnvios = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Vehiculos");

        mostrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar"));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        jLabel2.setText("Modelo:");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("12");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula"));

        jLabel4.setText("Marca:");

        jLabel5.setText("Vol. Carga(m2):");

        jLabel6.setText("Cap. Carga(Kg):");

        jLabel7.setText("Dist. recorrida(km):");

        modeloLabel.setText("jLabel8");

        marcaLabel.setText("jLabel9");

        capCargaLabel.setText("jLabel10");

        volCargaLabel.setText("jLabel11");

        kmRecorridosLabel.setText("jLabel12");

        jLabel11.setText("Servicio(km):");

        jLabel12.setText("jLabel12");

        jButton5.setText("Editar");

        jButton3.setText("Borrar");

        jButton4.setText("Servicio");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout mostrarLayout = new javax.swing.GroupLayout(mostrar);
        mostrar.setLayout(mostrarLayout);
        mostrarLayout.setHorizontalGroup(
            mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modeloLabel)
                            .addComponent(marcaLabel)
                            .addComponent(capCargaLabel)
                            .addComponent(volCargaLabel)
                            .addComponent(kmRecorridosLabel)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap())
        );
        mostrarLayout.setVerticalGroup(
            mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarLayout.createSequentialGroup()
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(modeloLabel)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(marcaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(capCargaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volCargaLabel)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kmRecorridosLabel)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrarLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        reportButton.setText("Reporte");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        vList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), javax.swing.UIManager.getDefaults().getColor("Panel.background"))); // NOI18N
        vList.setModel(vListModel);
        vList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(vList);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        registrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar"));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Modelo:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Marca:");

        marcasCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcasComboActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Cap. Carga:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Vol. Carga");

        openImageButton.setText("Cargar Imagen");
        openImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openImageButtonActionPerformed(evt);
            }
        });

        pathLabel.setText("...");

        registrarButton.setBackground(new java.awt.Color(255, 153, 0));
        registrarButton.setText("Registrar");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Año:");

        matrTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrTFActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Matricula:");

        javax.swing.GroupLayout registrarLayout = new javax.swing.GroupLayout(registrar);
        registrar.setLayout(registrarLayout);
        registrarLayout.setHorizontalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcasCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(12, 12, 12)
                                .addComponent(matrTF))
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrarLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(capCargaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(registrarLayout.createSequentialGroup()
                                        .addComponent(openImageButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(volCargaSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addComponent(registrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(registrarLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anioSpinner)))))
                .addContainerGap())
        );
        registrarLayout.setVerticalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(marcasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(capCargaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(volCargaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(anioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openImageButton)
                    .addComponent(pathLabel)
                    .addComponent(registrarButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout vehiculosTabLayout = new javax.swing.GroupLayout(vehiculosTab);
        vehiculosTab.setLayout(vehiculosTabLayout);
        vehiculosTabLayout.setHorizontalGroup(
            vehiculosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehiculosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vehiculosTabLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehiculosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        vehiculosTabLayout.setVerticalGroup(
            vehiculosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehiculosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vehiculosTabLayout.createSequentialGroup()
                        .addGroup(vehiculosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(vehiculosTabLayout.createSequentialGroup()
                        .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vehiculos", vehiculosTab);

        nuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo envío"));

        jLabel18.setText("Calle y número:");

        calleTF.setText("Malinalco");

        jLabel19.setText("Colonia:");

        coloniaTF.setText("El Barco");
        coloniaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloniaTFActionPerformed(evt);
            }
        });

        municipioTF.setText("Nezahualcoyotl");

        jLabel20.setText("Municipio");

        jLabel21.setText("Estado:");

        estadoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTFActionPerformed(evt);
            }
        });

        jLabel22.setText("Tipo de Envío:");

        jLabel23.setText("Entrega:");

        diaSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        diaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                diaSpinnerStateChanged(evt);
            }
        });

        jLabel24.setText("Dia");

        mesSpinner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesSpinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesSpinnerActionPerformed(evt);
            }
        });

        jLabel25.setText("Carga");

        buttonGroup1.add(cajasRadio);
        cajasRadio.setSelected(true);
        cajasRadio.setText("Cajas Estándar");
        cajasRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajasRadioActionPerformed(evt);
            }
        });

        cajasSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cajasSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cajasSpinnerStateChanged(evt);
            }
        });

        buttonGroup1.add(dimensionesRadio);
        dimensionesRadio.setText("Por dimensiones:");
        dimensionesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionesRadioActionPerformed(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Ancho:");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Alto:");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Profundidad:");

        anchoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anchoSpinnerStateChanged(evt);
            }
        });

        altoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                altoSpinnerStateChanged(evt);
            }
        });

        profSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                profSpinnerStateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        jlabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel23.setText("Total:");

        jlabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel24.setText("Precio(IVA):");

        costoLabel.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        costoLabel.setText("0");

        precioLabel.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        precioLabel.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel23)
                    .addComponent(jlabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel23)
                    .addComponent(costoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel24)
                    .addComponent(precioLabel))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel15.setText("Peso:");

        pesoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pesoSpinnerStateChanged(evt);
            }
        });

        anioSpinnerEnvio.setModel(new javax.swing.SpinnerNumberModel(2018, 2018, null, 1));
        anioSpinnerEnvio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anioSpinnerEnvioStateChanged(evt);
            }
        });

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoLayout = new javax.swing.GroupLayout(nuevo);
        nuevo.setLayout(nuevoLayout);
        nuevoLayout.setHorizontalGroup(
            nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(nuevoLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coloniaTF))
                    .addGroup(nuevoLayout.createSequentialGroup()
                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nuevoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoEnvioCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nuevoLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoTF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(nuevoLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anioSpinnerEnvio))))
                    .addGroup(nuevoLayout.createSequentialGroup()
                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(nuevoLayout.createSequentialGroup()
                                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nuevoLayout.createSequentialGroup()
                                        .addComponent(cajasRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(nuevoLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(dimensionesRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(anchoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nuevoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoLayout.createSequentialGroup()
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoLayout.createSequentialGroup()
                                                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel28))
                                                .addGap(12, 12, 12)))
                                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(profSpinner)
                                            .addComponent(altoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                            .addComponent(pesoSpinner))))))
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nuevoLayout.setVerticalGroup(
            nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(calleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coloniaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(estadoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoEnvioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(diaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioSpinnerEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajasRadio)
                    .addComponent(cajasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimensionesRadio)
                    .addComponent(jLabel26)
                    .addComponent(anchoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoLayout.createSequentialGroup()
                                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(profSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(pesoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nuevoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel30.setText("Buscar código:");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(buscarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reporteEnvios.setText(" Realizar Reporte");
        reporteEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteEnviosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout factuarasTabLayout = new javax.swing.GroupLayout(factuarasTab);
        factuarasTab.setLayout(factuarasTabLayout);
        factuarasTabLayout.setHorizontalGroup(
            factuarasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factuarasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(factuarasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(factuarasTabLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reporteEnvios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        factuarasTabLayout.setVerticalGroup(
            factuarasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factuarasTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(factuarasTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(factuarasTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, factuarasTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(reporteEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Envios", factuarasTab);

        jLabel31.setText("jLabel31");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        String calleNum = calleTF.getText();
        String colonia = coloniaTF.getText();
        String municipio = municipioTF.getText();
        int anio = Integer.parseInt(anioSpinnerEnvio.getValue().toString());
        if (calleNum.isEmpty() || colonia.isEmpty() || municipio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aún no llena los campos por completo");
            return;
        }
        Factura f = new Factura();
        f.setDir(new Direccion(calleNum, colonia, municipio, estadoTF.getSelectedItem().toString()));
        f.setFechaSalida(new Fecha(Calendar.getInstance().getTimeInMillis()));
        Fecha fecha = new Fecha(
                mesSpinner.getSelectedIndex(),//Mes
                Integer.parseInt(anioSpinnerEnvio.getValue().toString()),//Año
                Integer.parseInt(diaSpinner.getValue().toString()));
        f.setFechaEntrega(fecha);//Dia
        f.setTipoEnvio(tipoEnvioCombo.getSelectedItem().toString());
        f.setVolCarga(calcularVolumen());
        f.setPesoCarga(calcularPeso());
        float precio = calcularTarifa(fecha.getCalendar());
        f.setPrecioNeto(precio*(1+Configuracion.IVA));
        f.hash();
        try {
            db.nuevaFactura(f,estadoTF.getSelectedIndex()+1,1+tipoEnvioCombo.getSelectedIndex());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al procesar la transacción", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void cajasRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajasRadioActionPerformed
        dispTarifa();
    }//GEN-LAST:event_cajasRadioActionPerformed

    private void coloniaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloniaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coloniaTFActionPerformed

    private void matrTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrTFActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        File nuevaImg;
        String modelo = modeloTF.getText();
        String matricula = matrTF.getText();
        short marca = (short) (marcasCombo.getSelectedIndex() + 1);
        int capCarga = Integer.parseInt(capCargaSpinner.getValue().toString());
        int volCarga = Integer.parseInt(volCargaSpinner.getValue().toString());
        short anioFabr = Short.parseShort(anioSpinner.getValue().toString());
        if (modelo.isEmpty() || matricula.isEmpty() || capCarga == 0 || volCarga == 0 || anioFabr == 0) {
            JOptionPane.showMessageDialog(this, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            if (selectedImg == null) {
                db.nuevoVehiculo(matricula, marca, modelo, anioFabr, capCarga, volCarga, "");
            } else {
                nuevaImg = new File("src\\main\\resources\\" + matricula + selectedImg.getName());
                db.nuevoVehiculo(matricula, marca, modelo, anioFabr, capCarga, volCarga, nuevaImg.toPath().toString());
                Files.copy(selectedImg.toPath(), nuevaImg.toPath(), COPY_ATTRIBUTES);
            }
        } catch (IOException ex) {
            Logger.getLogger(VehiculosGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo satisfacer su solicitud", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex);
        }
        limpiarRegistro();
        JOptionPane.showMessageDialog(this, "Registro exitoso", "Atención", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void openImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openImageButtonActionPerformed
        fc.setMultiSelectionEnabled(false);
        fc.showOpenDialog(this);
        fc.addChoosableFileFilter(new ImgFilter());
        fc.setAcceptAllFileFilterUsed(false);
        try {
            System.out.println(fc.getSelectedFile().getCanonicalPath().toString());
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Tipo de archivo no soportado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener archivo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        selectedImg = fc.getSelectedFile();
        pathLabel.setText(selectedImg.getName());
        //Files.copy(Paths.get(f.getAbsolutePath()),Paths.get("resources",f.getName()), options);
    }//GEN-LAST:event_openImageButtonActionPerformed

    private void marcasComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcasComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcasComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vListModel.addElement("Evee");
        vList.setModel(vListModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        try {
            ReportesCSV.reporteVehiculos();
        } catch (IOException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al producir el reporte", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_reportButtonActionPerformed

    private void estadoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTFActionPerformed

    }//GEN-LAST:event_estadoTFActionPerformed

    private void mesSpinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesSpinnerActionPerformed
        dispTarifa();
    }//GEN-LAST:event_mesSpinnerActionPerformed

    private void diaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_diaSpinnerStateChanged
        dispTarifa();
    }//GEN-LAST:event_diaSpinnerStateChanged

    private void anioSpinnerEnvioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anioSpinnerEnvioStateChanged
        dispTarifa();
    }//GEN-LAST:event_anioSpinnerEnvioStateChanged

    private void cajasSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cajasSpinnerStateChanged
        dispTarifa();
    }//GEN-LAST:event_cajasSpinnerStateChanged

    private void dimensionesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionesRadioActionPerformed
        dispTarifa();
    }//GEN-LAST:event_dimensionesRadioActionPerformed

    private void anchoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anchoSpinnerStateChanged
        dispTarifa();
    }//GEN-LAST:event_anchoSpinnerStateChanged

    private void altoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_altoSpinnerStateChanged
        dispTarifa();
    }//GEN-LAST:event_altoSpinnerStateChanged

    private void profSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_profSpinnerStateChanged
        dispTarifa();
    }//GEN-LAST:event_profSpinnerStateChanged

    private void pesoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pesoSpinnerStateChanged
        dispTarifa();
    }//GEN-LAST:event_pesoSpinnerStateChanged

    private void reporteEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteEnviosActionPerformed
        try {
            ReportesCSV.reporteFacturas();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al escribir el archivo","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al procesar la transacción en la base de datos","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
        JOptionPane.showMessageDialog(this, "Reporte generado exitosamente","Reporte",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_reporteEnviosActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        Factura fact = new Factura();
        String key = buscarTF.getText().trim();
        try {
            fact = db.verFactura(key);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al procesar la transacción en la base de datos","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
        JOptionPane.showMessageDialog(this,"Identificador: "+fact.getKey(), "Envío", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void limpiarRegistro() {
        matrTF.setText("");
        modeloTF.setText("");
        marcasCombo.setSelectedIndex(0);
        volCargaSpinner.setValue(0);
        capCargaSpinner.setValue(0);
    }

    private void dispTarifa() {
        float tarifa = 0f;
        Fecha fecha = new Fecha(
                mesSpinner.getSelectedIndex(),//Mes
                Integer.parseInt(anioSpinnerEnvio.getValue().toString()),//Año
                Integer.parseInt(diaSpinner.getValue().toString()));//Dia
        tarifa = calcularTarifa(fecha.getCalendar());
        costoLabel.setText(numFormat.format(tarifa));
        precioLabel.setText(numFormat.format(tarifa * (1 + Configuracion.IVA)));
    }

    /**
     * Función que calcula la tarifa (sin IVA) del envío
     *
     * @param entrega - Fecha de entrega
     * @return la tarifa aplicable al cargamento
     */
    private float calcularTarifa(Calendar entrega) {
        float tarifa = 0f;
        Calendar c = Calendar.getInstance();
        //Instancia de calendario configurada al maximo de días para el 
        //envio expres
        int dias = diasDiferencia(c, entrega);
        if(dias < 0)
            return 0f;
        c.add(Calendar.DAY_OF_MONTH, Configuracion.RANGO_ENVIO_EXPRES);
        float vol = calcularVolumen();
        if (entrega.after(c)) {
            //Usar la tarifa normal
            tarifa = vol * Configuracion.TARIFA_BASICA;
        } else {
            //Tarifa expres
            tarifa = vol * Configuracion.TARIFA_EXPRES;
        }
        return dias * tarifa;
    }

    /**
     * Calcula la relación peso-volumen del paquete
     *
     * @return valor de la relación peso-volumen del paquete
     */
    private float calcularVolumen() {
        float res = 0f;
        if (dimensionesRadio.isSelected()) {
            float ancho = Float.parseFloat(anchoSpinner.getValue().toString());
            float alto = Float.parseFloat(altoSpinner.getValue().toString());
            float prof = Float.parseFloat(profSpinner.getValue().toString());
            float peso = Float.parseFloat(pesoSpinner.getValue().toString());
            res = ancho * alto * prof;
        } else {
            int cajas = Integer.parseInt(cajasSpinner.getValue().toString());
            res = cajas * Configuracion.CAJA_VOL;
        }
        return res;
    }
    private float calcularPeso(){
        float res = 0f;
        if (dimensionesRadio.isSelected()) {
            res = Float.parseFloat(pesoSpinner.getValue().toString());
        }else{
            int cajas = Integer.parseInt(cajasSpinner.getValue().toString());
            res = Configuracion.CAJA_PESO;
        }
        return res;
    }

    private int diasDiferencia(Calendar salida, Calendar entrega) {
        System.out.println("salida:" + salida.getTime().toString());
        System.out.println("entrega:" + entrega.getTime().toString());
        return Days.daysBetween(new LocalDateTime(salida.getTimeInMillis()), new LocalDateTime(entrega.getTimeInMillis())).getDays();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiculosGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner altoSpinner;
    private javax.swing.JSpinner anchoSpinner;
    private javax.swing.JSpinner anioSpinner;
    private javax.swing.JSpinner anioSpinnerEnvio;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cajasRadio;
    private javax.swing.JSpinner cajasSpinner;
    private javax.swing.JTextField calleTF;
    private javax.swing.JLabel capCargaLabel;
    private javax.swing.JSpinner capCargaSpinner;
    private javax.swing.JTextField coloniaTF;
    private javax.swing.JLabel costoLabel;
    private javax.swing.JSpinner diaSpinner;
    private javax.swing.JRadioButton dimensionesRadio;
    private javax.swing.JButton enviarButton;
    private javax.swing.JComboBox<String> estadoTF;
    private javax.swing.JPanel factuarasTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlabel23;
    private javax.swing.JLabel jlabel24;
    private javax.swing.JLabel kmRecorridosLabel;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JComboBox<String> marcasCombo;
    private javax.swing.JTextField matrTF;
    private javax.swing.JComboBox<String> mesSpinner;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField modeloTF;
    private javax.swing.JPanel mostrar;
    private javax.swing.JTextField municipioTF;
    private javax.swing.JPanel nuevo;
    private javax.swing.JButton openImageButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JSpinner pesoSpinner;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JSpinner profSpinner;
    private javax.swing.JPanel registrar;
    private javax.swing.JButton registrarButton;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton reporteEnvios;
    private javax.swing.JComboBox<String> tipoEnvioCombo;
    private javax.swing.JList<String> vList;
    private javax.swing.JPanel vehiculosTab;
    private javax.swing.JLabel volCargaLabel;
    private javax.swing.JSpinner volCargaSpinner;
    // End of variables declaration//GEN-END:variables

}
