/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worker.app;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import worker.sources.HourlyWorker;
import worker.sources.Worker;
import worker.sources.WorkerComparator;

/**
 *
 * @author alumno
 */
public class WorkerApp extends javax.swing.JFrame {

    List<Worker> employees;
    DefaultListModel emplListModel;

    public WorkerApp() {
        emplListModel = new DefaultListModel();
        employees = new ArrayList<>();
        initComponents();
        workersList.setModel(emplListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        workSinceField = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        workersList = new javax.swing.JList<>();
        nameLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        insWorker = new javax.swing.JButton();
        workedHoursField = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        insHourlyWorker = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        showWorker = new javax.swing.JButton();
        generateReportButton = new javax.swing.JButton();
        salaryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Trabajador");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Año de Ingreso");

        workSinceField.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)2018), Short.valueOf((short)1900), Short.valueOf((short)2018), Short.valueOf((short)1)));

        jLabel3.setText("Trabajadores");

        jLabel4.setText("Insertar");

        jLabel5.setText("Trabajadores");

        workersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(workersList);

        nameLabel.setText("Nombre:");

        yearLabel.setText("Año de Ingreso:");

        hourLabel.setText("Horas Trabajadas:");

        insWorker.setText("Insertar Trabajador");
        insWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insWorkerActionPerformed(evt);
            }
        });

        workedHoursField.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)1), Byte.valueOf((byte)1), Byte.valueOf((byte)12), Byte.valueOf((byte)1)));

        jLabel9.setText("Horas Trabajadas");

        insHourlyWorker.setText("Insertar Trabajador por Horas");
        insHourlyWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insHourlyWorkerActionPerformed(evt);
            }
        });

        idLabel.setText("ID:");

        showWorker.setBackground(new java.awt.Color(255, 102, 102));
        showWorker.setText("Mostrar Trabajador");
        showWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showWorkerActionPerformed(evt);
            }
        });

        generateReportButton.setBackground(new java.awt.Color(51, 153, 255));
        generateReportButton.setText("Reporte");
        generateReportButton.setToolTipText("Crear reporte de trabajadores\n");
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });

        salaryLabel.setText("Salario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(workSinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(insWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(workedHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(insHourlyWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(showWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(yearLabel)
                                    .addComponent(hourLabel)
                                    .addComponent(idLabel)
                                    .addComponent(salaryLabel))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel3)))
                        .addGap(116, 116, 116)
                        .addComponent(generateReportButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addComponent(generateReportButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(workSinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insWorker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workedHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(insHourlyWorker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hourLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showWorker)
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void showWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showWorkerActionPerformed
        int index = workersList.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "No hay trabajadores agregados", "Alerta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Worker tempWorker = employees.get(workersList.getSelectedIndex());
        nameLabel.setText("Nombre:" + tempWorker.getName());
        yearLabel.setText("Año de ingreso" + tempWorker.getWorkerSince());
        idLabel.setText("ID:" + tempWorker.getId());
        salaryLabel.setText("Salario:"+tempWorker.getSalary());
        if (employees.get(index) instanceof HourlyWorker) {
            HourlyWorker hw = (HourlyWorker) employees.get(index);
            hourLabel.setText(hw.getHours() + "Horas trabajadas:");
            return;
        }
        if (employees.get(index) instanceof Worker) {
            hourLabel.setText("Horas trabajadas:-");
        }
    }//GEN-LAST:event_showWorkerActionPerformed

    private void insWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insWorkerActionPerformed
        Worker wk = new Worker(nameField.getText(), Short.valueOf(workSinceField.getValue().toString()));
        wk.assignId();
        wk.assignSalary();
        employees.add(wk);
        emplListModel.addElement(wk.getName() + "(" + wk.getId() + ")");
    }//GEN-LAST:event_insWorkerActionPerformed

    private void insHourlyWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insHourlyWorkerActionPerformed
        HourlyWorker wk = new HourlyWorker(nameField.getText(), Short.valueOf(workSinceField.getValue().toString()), Byte.parseByte(workedHoursField.getValue().toString()));
        wk.assignId();
        wk.assignSalary();
        employees.add(wk);
        emplListModel.addElement(wk.getName() + "(" + wk.getId() + ")");
    }//GEN-LAST:event_insHourlyWorkerActionPerformed

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        Collections.sort(employees, new WorkerComparator());
        StringBuilder reportText = new StringBuilder();
        for (Worker employee : employees) {
            reportText.append("Nombre:").append(employee.getName()).append("\n");
            reportText.append("ID:").append(employee.getId()).append("\n");
            reportText.append("Año de ingreso:").append(employee.getWorkerSince()).append("\n");
            reportText.append("Salario").append(employee.getSalary()).append("\n");
            if (employee instanceof HourlyWorker) {
                HourlyWorker hw = (HourlyWorker) employee;
                reportText.append("Horas trabajadas:").append(((HourlyWorker) employee).getHours()).append("\n");
                reportText.append("==============================\n");
                continue;
            }
            if (employee instanceof Worker) {
                reportText.append("Horas trabajadas:-\n");
            }
            reportText.append("==============================\n");
        }
        JDialog repoDiag = new JDialog(this,"Reporte");
        repoDiag.setSize(200, 300);
        repoDiag.add(new JTextArea(reportText.toString()));
        repoDiag.setVisible(true);
        //JOptionPane.showInputDialog(this, "Reporte:",reportText.toString());
//JOptionPane.showMessageDialog(this, reportText.toString(),"Reporte",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_generateReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportButton;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton insHourlyWorker;
    private javax.swing.JButton insWorker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JButton showWorker;
    private javax.swing.JSpinner workSinceField;
    private javax.swing.JSpinner workedHoursField;
    private javax.swing.JList<String> workersList;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
