package app;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import sources.Ave;
import sources.El_Santo;
import sources.Fecha;

public class VoladoresApp extends javax.swing.JFrame {

    private Ave ave;
    private El_Santo elSanto;

    public VoladoresApp() {
        initComponents();
        setStateActAve(false);
        setStateActLuch(false);
        setStateActVol(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nuevoLuchadorButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        luchCapaAntiToggle = new javax.swing.JToggleButton();
        luchMascPlataToggle = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        luchCampGanSpinner = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        luchMatVampButton = new javax.swing.JButton();
        luchMatMomButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        luchDormButton = new javax.swing.JButton();
        luchCorrButton = new javax.swing.JButton();
        luchDesvelarButton = new javax.swing.JButton();
        luchDesvHhrSpinner = new javax.swing.JSpinner();
        luchGanarButton = new javax.swing.JButton();
        luchPerderButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nuevaAveButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        aveNombreTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aveDiaNacSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aveMesNacCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        aveAnioNacSpinner = new javax.swing.JSpinner();
        aveNombCientTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        avePeligroExtToggle = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        aveTipoAlasTf = new javax.swing.JTextField();
        aveDepredadorToggle = new javax.swing.JToggleButton();
        jPanel11 = new javax.swing.JPanel();
        avePonerHuevoButton = new javax.swing.JButton();
        aveEmpollarButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        volDespegarButton = new javax.swing.JButton();
        volVolarButton = new javax.swing.JButton();
        volAterrizarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(210, 218, 226));

        jPanel1.setBackground(new java.awt.Color(255, 63, 52));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/mexican-mask.png"))); // NOI18N
        jLabel1.setText("El Santo");

        nuevoLuchadorButton.setBackground(new java.awt.Color(30, 39, 46));
        nuevoLuchadorButton.setForeground(new java.awt.Color(255, 255, 255));
        nuevoLuchadorButton.setText("Nuevo");
        nuevoLuchadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoLuchadorButtonActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 63, 52));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atributos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        luchCapaAntiToggle.setBackground(new java.awt.Color(30, 39, 46));
        luchCapaAntiToggle.setForeground(new java.awt.Color(255, 255, 255));
        luchCapaAntiToggle.setText("Capa Antibalas:Desactivada");
        luchCapaAntiToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchCapaAntiToggleActionPerformed(evt);
            }
        });

        luchMascPlataToggle.setBackground(new java.awt.Color(30, 39, 46));
        luchMascPlataToggle.setForeground(new java.awt.Color(255, 255, 255));
        luchMascPlataToggle.setText("Mascara de Plata:Desactivada");
        luchMascPlataToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchMascPlataToggleActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 63, 52));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atleta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Campeonatos Ganados:");

        luchCampGanSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luchCampGanSpinner)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(luchCampGanSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(luchMascPlataToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(luchCapaAntiToggle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(luchCapaAntiToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luchMascPlataToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 63, 52));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        luchMatVampButton.setBackground(new java.awt.Color(30, 39, 46));
        luchMatVampButton.setForeground(new java.awt.Color(255, 255, 255));
        luchMatVampButton.setText("Matar Vampiros");
        luchMatVampButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchMatVampButtonActionPerformed(evt);
            }
        });

        luchMatMomButton.setBackground(new java.awt.Color(30, 39, 46));
        luchMatMomButton.setForeground(new java.awt.Color(255, 255, 255));
        luchMatMomButton.setText("Matar Momias");
        luchMatMomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchMatMomButtonActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 63, 52));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atleta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        luchDormButton.setBackground(new java.awt.Color(30, 39, 46));
        luchDormButton.setForeground(new java.awt.Color(255, 255, 255));
        luchDormButton.setText("Dormir");
        luchDormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchDormButtonActionPerformed(evt);
            }
        });

        luchCorrButton.setBackground(new java.awt.Color(30, 39, 46));
        luchCorrButton.setForeground(new java.awt.Color(255, 255, 255));
        luchCorrButton.setText("Correr");
        luchCorrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchCorrButtonActionPerformed(evt);
            }
        });

        luchDesvelarButton.setBackground(new java.awt.Color(30, 39, 46));
        luchDesvelarButton.setForeground(new java.awt.Color(255, 255, 255));
        luchDesvelarButton.setText("Desvelar(Horas)");
        luchDesvelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchDesvelarButtonActionPerformed(evt);
            }
        });

        luchDesvHhrSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 36, 1));

        luchGanarButton.setBackground(new java.awt.Color(30, 39, 46));
        luchGanarButton.setForeground(new java.awt.Color(255, 255, 255));
        luchGanarButton.setText("Ganar");
        luchGanarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchGanarButtonActionPerformed(evt);
            }
        });

        luchPerderButton.setBackground(new java.awt.Color(30, 39, 46));
        luchPerderButton.setForeground(new java.awt.Color(255, 255, 255));
        luchPerderButton.setText("Perder");
        luchPerderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luchPerderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(luchCorrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(luchDormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(luchDesvelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(luchDesvHhrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(luchGanarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(luchPerderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luchDormButton)
                    .addComponent(luchCorrButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luchDesvelarButton)
                    .addComponent(luchDesvHhrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luchPerderButton)
                    .addComponent(luchGanarButton)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luchMatVampButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(luchMatMomButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luchMatVampButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luchMatMomButton))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevoLuchadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nuevoLuchadorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel2.setBackground(new java.awt.Color(0, 216, 214));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 39, 46));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/dove-.png"))); // NOI18N
        jLabel2.setText("Ave");

        nuevaAveButton.setBackground(new java.awt.Color(30, 39, 46));
        nuevaAveButton.setForeground(new java.awt.Color(255, 255, 255));
        nuevaAveButton.setText("Nuevo");
        nuevaAveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaAveButtonActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(0, 216, 214));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atributos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(30, 39, 46))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(0, 216, 214));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(30, 39, 46))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(30, 39, 46));
        jLabel5.setText("Nombre:");

        jLabel6.setForeground(new java.awt.Color(30, 39, 46));
        jLabel6.setText("Fecha de Nacimiento:");

        aveDiaNacSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel7.setForeground(new java.awt.Color(30, 39, 46));
        jLabel7.setText("Dia:");

        jLabel8.setForeground(new java.awt.Color(30, 39, 46));
        jLabel8.setText("Mes:");

        aveMesNacCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel12.setForeground(new java.awt.Color(30, 39, 46));
        jLabel12.setText("Año:");

        aveAnioNacSpinner.setModel(new javax.swing.SpinnerNumberModel(2018, 1900, 2018, 1));

        jLabel13.setForeground(new java.awt.Color(30, 39, 46));
        jLabel13.setText("Nombre Científico:");

        avePeligroExtToggle.setBackground(new java.awt.Color(30, 39, 46));
        avePeligroExtToggle.setForeground(new java.awt.Color(255, 255, 255));
        avePeligroExtToggle.setText("Peligro de Extinción:No");
        avePeligroExtToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avePeligroExtToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avePeligroExtToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aveNombreTf)
                            .addComponent(aveNombCientTf)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aveDiaNacSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aveMesNacCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aveAnioNacSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aveNombreTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aveNombCientTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aveDiaNacSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(aveMesNacCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(aveAnioNacSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avePeligroExtToggle))
        );

        jLabel14.setForeground(new java.awt.Color(30, 39, 46));
        jLabel14.setText("Tipo de Alas:");

        aveDepredadorToggle.setBackground(new java.awt.Color(30, 39, 46));
        aveDepredadorToggle.setForeground(new java.awt.Color(255, 255, 255));
        aveDepredadorToggle.setText("Depredador:No");
        aveDepredadorToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aveDepredadorToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aveDepredadorToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aveTipoAlasTf)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(aveTipoAlasTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aveDepredadorToggle))
        );

        jPanel11.setBackground(new java.awt.Color(0, 216, 214));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(30, 39, 46))); // NOI18N

        avePonerHuevoButton.setBackground(new java.awt.Color(30, 39, 46));
        avePonerHuevoButton.setForeground(new java.awt.Color(255, 255, 255));
        avePonerHuevoButton.setText("Poner Huevo");
        avePonerHuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avePonerHuevoButtonActionPerformed(evt);
            }
        });

        aveEmpollarButton.setBackground(new java.awt.Color(30, 39, 46));
        aveEmpollarButton.setForeground(new java.awt.Color(255, 255, 255));
        aveEmpollarButton.setText("Empollar");
        aveEmpollarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aveEmpollarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avePonerHuevoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aveEmpollarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(avePonerHuevoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aveEmpollarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevaAveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nuevaAveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(210, 218, 226));

        output.setBackground(new java.awt.Color(128, 142, 155));
        output.setColumns(20);
        output.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        output.setForeground(new java.awt.Color(30, 39, 46));
        output.setRows(5);
        output.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)), "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(30, 39, 46))); // NOI18N
        jScrollPane1.setViewportView(output);

        volDespegarButton.setBackground(new java.awt.Color(30, 39, 46));
        volDespegarButton.setForeground(new java.awt.Color(255, 255, 255));
        volDespegarButton.setText("Despegar");
        volDespegarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volDespegarButtonActionPerformed(evt);
            }
        });

        volVolarButton.setBackground(new java.awt.Color(30, 39, 46));
        volVolarButton.setForeground(new java.awt.Color(255, 255, 255));
        volVolarButton.setText("Volar");
        volVolarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volVolarButtonActionPerformed(evt);
            }
        });

        volAterrizarButton.setBackground(new java.awt.Color(30, 39, 46));
        volAterrizarButton.setForeground(new java.awt.Color(255, 255, 255));
        volAterrizarButton.setText("Aterrizar");
        volAterrizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volAterrizarButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 39, 46));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Voladores");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(volDespegarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(volVolarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(volAterrizarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(11, 11, 11))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volDespegarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volVolarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(volAterrizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luchMascPlataToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchMascPlataToggleActionPerformed
        if(luchMascPlataToggle.isSelected())
            luchMascPlataToggle.setText("Mascara de Plata:Activada");
        else
            luchMascPlataToggle.setText("Mascara de Plata:Desactivada");
    }//GEN-LAST:event_luchMascPlataToggleActionPerformed

    private void luchCorrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchCorrButtonActionPerformed
        elSanto.correr();
        output.setText(elSanto.toString());
    }//GEN-LAST:event_luchCorrButtonActionPerformed

    private void luchGanarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchGanarButtonActionPerformed
        elSanto.win();
        output.setText(elSanto.toString());
    }//GEN-LAST:event_luchGanarButtonActionPerformed

    private void nuevoLuchadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoLuchadorButtonActionPerformed
        ave = null;
        elSanto = new El_Santo(luchMascPlataToggle.isSelected(), luchCapaAntiToggle.isSelected());
        elSanto.setChampionWins(Integer.parseInt(luchCampGanSpinner.getValue().toString()));
        //Activar campos de actividad de luchador
        setStateActLuch(true);
        //Desactivar campos de Ave
        setStateActAve(false);
        setStateActVol(true);
        output.setText("Nuevo Luchador:\n" + elSanto.toString());
    }//GEN-LAST:event_nuevoLuchadorButtonActionPerformed

    private void luchDormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchDormButtonActionPerformed
        elSanto.dormir();
        output.setText(elSanto.toString());
    }//GEN-LAST:event_luchDormButtonActionPerformed

    private void luchDesvelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchDesvelarButtonActionPerformed
        elSanto.desvelarse(Integer.parseInt(luchDesvHhrSpinner.getValue().toString()));
        output.setText(elSanto.toString());
    }//GEN-LAST:event_luchDesvelarButtonActionPerformed

    private void luchPerderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchPerderButtonActionPerformed
        elSanto.lose();
        output.setText(elSanto.toString());
    }//GEN-LAST:event_luchPerderButtonActionPerformed

    private void luchMatVampButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchMatVampButtonActionPerformed
        output.setText("Vampiros muertos: " + elSanto.matarVampiros() + "\n" + elSanto.toString());
    }//GEN-LAST:event_luchMatVampButtonActionPerformed

    private void luchMatMomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchMatMomButtonActionPerformed
        output.setText("Momias muertas: " + elSanto.matarMomiasGto() + "\n" + elSanto.toString());
    }//GEN-LAST:event_luchMatMomButtonActionPerformed

    private void nuevaAveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaAveButtonActionPerformed
        elSanto = null;
        ave = new Ave(aveNombreTf.getText(),
                new Fecha(
                        aveDiaNacSpinner.getValue().toString(),
                        aveMesNacCombo.getSelectedItem().toString(),
                        aveAnioNacSpinner.getValue().toString()),
                aveNombCientTf.getText(),
                avePeligroExtToggle.isSelected(),
                aveDepredadorToggle.isSelected(),
                aveTipoAlasTf.getText());
        setStateActAve(true);
        setStateActLuch(false);
        setStateActVol(true);
        output.setText("Nueva Ave\n" + ave.toString());
    }//GEN-LAST:event_nuevaAveButtonActionPerformed

    private void volDespegarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volDespegarButtonActionPerformed
        if (ave == null) {
            output.setText(elSanto.despegar());
        }
        if (elSanto == null) {
            output.setText(ave.despegar());
        }
    }//GEN-LAST:event_volDespegarButtonActionPerformed

    private void volVolarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volVolarButtonActionPerformed
        if (ave == null) {
            output.setText(elSanto.volar());
        }
        if (elSanto == null) {
            output.setText(ave.volar());
        }    }//GEN-LAST:event_volVolarButtonActionPerformed

    private void volAterrizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volAterrizarButtonActionPerformed
        if (ave == null) {
            output.setText(elSanto.aterrizar());
        }
        if (elSanto == null) {
            output.setText(ave.aterrizar());
        }    }//GEN-LAST:event_volAterrizarButtonActionPerformed

    private void avePonerHuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avePonerHuevoButtonActionPerformed
        output.setText("Huevos puestos:" + ave.ponerHuevo() + "\n" + ave.toString());
    }//GEN-LAST:event_avePonerHuevoButtonActionPerformed

    private void aveEmpollarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aveEmpollarButtonActionPerformed
        output.setText(ave.empollar() + "\n" + ave.toString());
    }//GEN-LAST:event_aveEmpollarButtonActionPerformed

    private void luchCapaAntiToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luchCapaAntiToggleActionPerformed
        if(luchCapaAntiToggle.isSelected())
            luchCapaAntiToggle.setText("Capa Antibalas:Activada");
        else
            luchCapaAntiToggle.setText("Capa Antibalas:Desactivada");
    }//GEN-LAST:event_luchCapaAntiToggleActionPerformed

    private void avePeligroExtToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avePeligroExtToggleActionPerformed
        if(avePeligroExtToggle.isSelected())
            avePeligroExtToggle.setText("Peligro de Extinción:Si");
        else
            avePeligroExtToggle.setText("Peligro de Extinción:No");
    }//GEN-LAST:event_avePeligroExtToggleActionPerformed

    private void aveDepredadorToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aveDepredadorToggleActionPerformed
        if(aveDepredadorToggle.isSelected())
            avePeligroExtToggle.setText("Depredador:Si");
        else
            avePeligroExtToggle.setText("Depredador:No");
    }//GEN-LAST:event_aveDepredadorToggleActionPerformed

    private void setStateAttrLuch(boolean state) {
        this.luchCapaAntiToggle.setEnabled(state);
        this.luchCampGanSpinner.setEnabled(state);
        this.luchMascPlataToggle.setEnabled(state);
    }

    private void setStateActLuch(boolean state) {
        this.luchCorrButton.setEnabled(state);
        this.luchDesvHhrSpinner.setEnabled(state);
        this.luchDesvelarButton.setEnabled(state);
        this.luchDormButton.setEnabled(state);
        this.luchGanarButton.setEnabled(state);
        this.luchMatMomButton.setEnabled(state);
        this.luchMatVampButton.setEnabled(state);
        this.luchPerderButton.setEnabled(state);
    }

    private void setStateAttrAve(boolean state) {
        this.aveAnioNacSpinner.setEnabled(state);
        this.aveDepredadorToggle.setEnabled(state);
        this.aveDiaNacSpinner.setEnabled(state);
        this.aveMesNacCombo.setEnabled(state);
        this.aveNombCientTf.setEnabled(state);
        this.aveNombreTf.setEnabled(state);
        this.avePeligroExtToggle.setEnabled(state);
        this.aveTipoAlasTf.setEnabled(state);
    }

    private void setStateActAve(boolean state) {
        this.avePonerHuevoButton.setEnabled(state);
        this.aveEmpollarButton.setEnabled(state);
    }

    private void setStateActVol(boolean state) {
        this.volAterrizarButton.setEnabled(state);
        this.volDespegarButton.setEnabled(state);
        this.volVolarButton.setEnabled(state);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoladoresApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoladoresApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoladoresApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoladoresApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoladoresApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aveAnioNacSpinner;
    private javax.swing.JToggleButton aveDepredadorToggle;
    private javax.swing.JSpinner aveDiaNacSpinner;
    private javax.swing.JButton aveEmpollarButton;
    private javax.swing.JComboBox<String> aveMesNacCombo;
    private javax.swing.JTextField aveNombCientTf;
    private javax.swing.JTextField aveNombreTf;
    private javax.swing.JToggleButton avePeligroExtToggle;
    private javax.swing.JButton avePonerHuevoButton;
    private javax.swing.JTextField aveTipoAlasTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner luchCampGanSpinner;
    private javax.swing.JToggleButton luchCapaAntiToggle;
    private javax.swing.JButton luchCorrButton;
    private javax.swing.JSpinner luchDesvHhrSpinner;
    private javax.swing.JButton luchDesvelarButton;
    private javax.swing.JButton luchDormButton;
    private javax.swing.JButton luchGanarButton;
    private javax.swing.JToggleButton luchMascPlataToggle;
    private javax.swing.JButton luchMatMomButton;
    private javax.swing.JButton luchMatVampButton;
    private javax.swing.JButton luchPerderButton;
    private javax.swing.JButton nuevaAveButton;
    private javax.swing.JButton nuevoLuchadorButton;
    private javax.swing.JTextArea output;
    private javax.swing.JButton volAterrizarButton;
    private javax.swing.JButton volDespegarButton;
    private javax.swing.JButton volVolarButton;
    // End of variables declaration//GEN-END:variables
}
